### Update country
PUT http://localhost:8080/countries/68dda182ba923aa1896d2de3 HTTP/1.1
content-type: application/json

{
    "name": "JapanTest",
    "iso_code": "JP",
    "capital": "Tokyo",
    "region": "Asia",
    "subregion": "Eastern Asia",
    "population": 123294513,
    "area_km2": 377975,
    "currency": {
        "name": "Yen",
        "code": "JPY",
        "symbol": "¥"
    },
    "languages": ["Japanese"],
    "timezones": ["UTC+09:00"],
    "calling_code": "+81",
    "flag_url": "https://flagcdn.com/jp.svg"
}

### Delete country
DELETE http://localhost:8080/countries/68dda182ba923aa1896d2de3



### Update landmark
PUT http://localhost:8080/landmarks/68dda88e8c66150995ddb766 HTTP/1.1
content-type: application/json

{
    "name": "Tokyo Tower Test",
    "city": "Tokyo",
    "country": "Japan",
    "continent": "Asia",
    "type": "Observation Tower",
    "year_built": 1958,
    "height_m": 333,
    "visitors_per_year": 3000000,
    "coordinates": {
        "latitude": 35.6586,
        "longitude": 139.7454
    },
    "description": "A famous landmark in Tokyo...",
    "image_url": "https://example.com/tokyo-tower.jpg"
}

### Delete landmark
DELETE http://localhost:8080/landmarks/68dda88e8c66150995ddb766

### Update continent
PUT http://localhost:8080/continents/68e67024a6af0204628d6015 HTTP/1.1
content-type: application/json

{
"name": "Antartica Test",
"area_km2": 14000000,
"population": 5000,
"number_of_countries": 0,
"largest_country": "test",
"largest_city": "test",
"languages_major": [
    "English",
    "Russian"
],
"timezone_range": [
    "Varies"
],
"description": "Antarctica is the coldest continent, covered by ice sheets, with research stations but no permanent residents.",
"image_url": "https://example.com/images/antarctica.jpg"
}

### Delete continent
DELETE http://localhost:8080/continents/68e67024a6af0204628d6015

### Update city
PUT http://localhost:8080/cities/68dda163ba923aa1896d2dd0 HTTP/1.1
content-type: application/json

{
"name": "Cape Town",
"country": "South Africa",
"continent": "Africa",
"population": 4337000,
"area_km2": 2460,
"timezone": "UTC+02:00",
"coordinates": {
"latitude": -33.9249,
"longitude": 18.4241
},
"description": "Coastal city under Table Mountain, known for natural beauty and diversity.",
"image_url": "https://example.com/images/capetown.jpg"
}

### Delete city
DELETE http://localhost:8080/cities/68dda163ba923aa1896d2dd0